---
- hosts: all
  user: ec2-user
  become: yes
  tasks:
  - name: "Configring docker-ce repo"
    get_url:
     url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     dest: /tmp/epel-release-latest-7.noarch.rpm
     mode: 0644
  - name: " Installing Docker latest version"
    yum:
     name: /tmp/epel-release-latest-7.noarch.rpm
     state: present
  - name: "Installing Docker Prerequisite packages"
    yum:
     name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2','docker-1.13.1']
     state: latest
    # with_items:
    # - yum-utils
    # - device-mapper-persistent-data
    # - lvm2
    # ,'docker-1.13.1-102.git7f2769b.el7.x86_64'

  - name: " Starting and Enabling Docker service"
    service:
     name: docker
     state: started
     enabled: yes
