---
- hosts: all
  user: ec2-user
  become: yes
  tasks:
  # - name: "On eacConfigring rpmh host, register with RHSM"
  #   shell: subscription-manager register --username=ec2-user --password=ec2-user
  - name: "Pull the latest subscription data from RHSM"
    shell: subscription-manager refresh    
  - name: "List the available subscriptions:"
    shell: subscription-manager list --available --matches '*OpenShift*'   
  - name: "Configring rpm"
    shell: yum-config-manager --disable \*
  - name: "Configring rpm"
    shell: | 
      subscription-manager repos \
      --enable="rhel-7-server-rpms" \
      --enable="rhel-7-server-extras-rpms" \
      --enable="rhel-7-server-ose-3.11-rpms" \
      --enable="rhel-7-server-ansible-2.6-rpms"
  - name: "Configring rpm"
    shell: yum install docker-1.13.1